apiVersion: v1
kind: Service
metadata:
  name: {{ include "echoview-prometheus.fullname" . }}
  labels:
    {{- include "echoview-prometheus.serviceLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "echoview-prometheus.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
